extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python3 ./impl.py",
    "brili -p",
]
