extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "python3 ./bench.py",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python3 ./licm.py",
    "brili -p {args}",
]
